export const products = [
	{id:1,
		name: "adidas",
		description: [
			{ support: "گارانتی دار" },
			{ support: "ارسال رایگان" },
			{ support: "اصل" },
		],
		price: 120,
		offprice: 100,
		discount: 0,
		image: "https://s4.uupload.ir/files/item1_soj.jpg",
	},
    {
		id:2,
		name: "cat",
		description: [
			{ support: "گارانتی دار" },
			{ support: "ارسال رایگان" },
			{ support: "اصل" },
		],
		price: 120,
		offprice: 100,
		discount: 0,
		image: "https://s4.uupload.ir/files/item1_soj.jpg",
	},	{
		id:3,
		name: "jagvar",
		description: [
			{ support: "گارانتی دار" },
			{ support: "ارسال رایگان" },
			{ support: "اصل" },
		],
		price: 120,
		offprice: 100,
		discount: 0,
		image: "https://s4.uupload.ir/files/item1_soj.jpg",
	},	{
		id:4,
		name: "lacoust",
		description: [
			{ support: "گارانتی دار" },
			{ support: "ارسال رایگان" },
			{ support: "اصل" },
		],
		price: 120,
		offprice: 100,
		discount: 0,
		image: "https://s4.uupload.ir/files/item1_soj.jpg",
	},	{
		id:5,
		name: "amiri",
		description: [
			{ support: "گارانتی دار" },
			{ support: "ارسال رایگان" },
			{ support: "اصل" },
		],
		price: 120,
		offprice: 100,
		discount: 0,
		image: "https://s4.uupload.ir/files/item1_soj.jpg",
	},	{
		id:6,
		name: "adidas",
		description: [
			{ support: "گارانتی دار" },
			{ support: "ارسال رایگان" },
			{ support: "اصل" },
		],
		price: 120,
		offprice: 100,
		discount: 0,
		image: "https://s4.uupload.ir/files/item1_soj.jpg",
	},	{
		id:7,
		name: "zara",
		description: [
			{ support: "گارانتی دار" },
			{ support: "ارسال رایگان" },
			{ support: "اصل" },
		],
		price: 120,
		offprice: 100,
		discount: 0,
		image: "https://s4.uupload.ir/files/item3_zvc9.jpg",
	},	{
		id:8,
		name: "guuci",
		description: [
			{ support: "گارانتی دار" },
			{ support: "ارسال رایگان" },
			{ support: "اصل" },
		],
		price: 120,
		offprice: 100,
		discount: 0,
		image: "https://s4.uupload.ir/files/item2_fc5s.jpg",
	},	{
		id:9,
		name: "nike",
		description: [
			{ support: "گارانتی دار" },
			{ support: "ارسال رایگان" },
			{ support: "اصل" },
		],
		price: 120,
		offprice: 100,
		discount: 0,
		image: "https://s4.uupload.ir/files/item1_soj.jpg",
	},
];
